"""MUC phreeqc — PHREEQC input generation and result parsing adapter.

PHREEQC (Parkhurst & Appelo 2013, S33) is the standard geochemical speciation
engine. This skill runs fully offline with its own equilibrium solver, but for
validation and advanced modeling (ion-association models, mineral databases,
sorption) it can generate a valid PHREEQC input deck from the same input
envelope and parse a PHREEQC .out file's selected-output block back into the
skill's machine-readable result format.

Design:
  - `generate_input`: writes a PHREEQC input deck (SOLUTION + REACTION +
    SELECTED_OUTPUT) to stdout/file. No PHREEQC needed to generate it.
  - `run`: executes phreeqc binary if present; if absent, returns a structured
    MUC-E3001 error and (optionally) the generated deck so the caller can run
    it externally. This is the graceful offline degradation path.
  - `parse_output`: reads a PHREEQC selected-output table (pipe-delimited,
    `-reset false`) and converts to the skill's species/SI dict.

PHREEQC must be installed separately (USGS, see references S33); this skill
never bundles or downloads it. The deck uses the `phreeqc.dat` (or `minteq.dat`
if requested) database and an explicit REACTION for ureolysis products so the
results are comparable to the built-in engine.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys

from .errors import MUCError


def generate_input(
    *,
    ph: float | None,
    c_total: float,
    ca_total: float,
    t_k: float = 298.15,
    mg_total: float = 0.0,
    nh4_total: float = 0.0,
    cl_total: float = 0.0,
    na_total: float = 0.0,
    urea_initial: float = 0.0,
    database: str = "phreeqc.dat",
    label: str = "micp_ureolysis",
) -> str:
    """Generate a PHREEQC input deck.

    If `ph` is given, SOLUTION is defined with fixed pH and the carbonate and
    Ca totals; otherwise the deck defines total C, total Ca, and lets PHREEQC
    compute equilibrium. Ureolysis is represented as a REACTION that adds
    hydrolysis products (2 NH4 + 1 CO3, charge-balanced via Cl) — equivalent to
    the built-in stoichiometry.
    """
    if t_k <= 0:
        raise MUCError("MUC-E2004", f"phreeqc.generate_input: invalid t_k {t_k}")
    temp_c = t_k - 273.15
    lines = [
        "# PHREEQC input generated by MUC (micp-ureolysis-chemistry) — do not hand-edit unless you know what you are doing",
        f"# label: {label}",
        "",
        "SOLUTION 1",
        f"    temp {temp_c:.2f}",
        f"    pH {ph if ph is not None else 7.0}",
        f"    Ca {ca_total:.6e}",
        f"    C({4}) {c_total:.6e}",  # total inorganic carbon as CO3(2-)
        f"    Cl {cl_total:.6e}",
    ]
    if na_total > 0:
        lines.append(f"    Na {na_total:.6e}")
    if mg_total > 0:
        lines.append(f"    Mg {mg_total:.6e}")
    if nh4_total > 0:
        # NH4+ is nitrogen in oxidation state -3 (N(-3)); N(5) would be nitrate.
        lines.append(f"    N(-3) {nh4_total:.6e}   # NH4")
    lines.append("    -water 1 # kg")
    lines.append("")
    if urea_initial > 0:
        # Represent hydrolysis as a reaction step adding 2 NH4 + 1 CO3 (+ charge
        # balance via the SOLUTION already present). moles are per kg water;
        # ureolysis of `urea_initial` moles yields 2x NH4 and 1x CO3.
        lines.append("REACTION 1")
        lines.append(f"    NH4+ {2.0 * urea_initial:.6e}")
        lines.append(f"    CO3-2 {urea_initial:.6e}")
        lines.append(f"    1.0")  # single step (complete hydrolysis in one shot)
        lines.append("")
    lines.append("SELECTED_OUTPUT")
    lines.append("    -file selected.tmp")
    lines.append("    -reset false")
    lines.append("    -totals H+ Ca Mg Cl Na C(4) N(5)")
    lines.append("    -si calcite aragonite vaterite")
    lines.append("    -saturation_indices CaCO3(a)")
    lines.append("    -activities Ca+2 CO3-2")
    lines.append("    -water")
    lines.append("")
    lines.append("END")
    lines.append("")
    return "\n".join(lines)


def run(
    *,
    input_text: str,
    timeout_s: float = 30.0,
    phreeqc_bin: str | None = None,
) -> dict:
    """Run PHREEQC on the given deck.

    Returns {"ok": true, "raw_output": <the .out file text>} on success, or a
    structured MUC-E3001 error envelope when PHREEQC is unavailable.
    """
    binary = phreeqc_bin or os.environ.get("PHREEQC_BIN") or shutil.which("phreeqc")
    if not binary:
        raise MUCError(
            "MUC-E3001",
            "PHREEQC binary not found (tried $PHREEQC_BIN, PATH). This skill runs offline "
            "with its own solver; for PHREEQC validation install phreeqc (USGS) and set "
            "PHREEQC_BIN or PATH. The generated deck is returned in 'generated_input'.",
            details={"hint": "USGS PHREEQC: https://www.usgs.gov/software/phreeqc-version-3"},
        )
    try:
        proc = subprocess.run(
            [binary, input_text],
            input="",
            capture_output=True,
            text=True,
            timeout=timeout_s,
        )
    except subprocess.TimeoutExpired:
        raise MUCError("MUC-E3002", f"PHREEQC run timed out after {timeout_s}s", retryable=True)
    except OSError as exc:
        raise MUCError("MUC-E3001", f"failed to execute PHREEQC {binary!r}: {exc}", retryable=True)
    if proc.returncode != 0:
        raise MUCError(
            "MUC-E3002",
            f"PHREEQC exited {proc.returncode}; stderr: {proc.stderr[:500]}",
        )
    return {"ok": True, "raw_output": proc.stdout}


def parse_output(raw: str) -> dict:
    """Parse a PHREEQC selected-output pipe table into a machine-readable dict.

    Expects the `-reset false` format: header row, then per-step rows separated
    by `-`. Returns species activities, SI values, and totals. Robust to
    PHREEQC's `1.0e+000` formatting.
    """
    result: dict = {"si": {}, "activities": {}, "totals": {}, "steps": []}
    lines = [l for l in raw.splitlines() if l.strip() and not l.startswith("#")]
    # Find the selected-output block.
    idx = next((i for i, l in enumerate(lines) if "Saturation indices" in l or "si_" in l or l.startswith("Total")), None)
    if idx is None:
        # Fallback: parse the pipe table directly.
        for l in lines:
            if "|" in l:
                parts = [p.strip() for p in l.split("|")]
                if not parts or not parts[0]:
                    continue
                try:
                    key = parts[0]
                    val = float(parts[1])
                except (ValueError, IndexError):
                    continue
                if "si(" in key.lower() or "saturation" in key.lower():
                    result["si"][key] = val
                elif key.lower().startswith("act("):
                    result["activities"][key] = val
                else:
                    result["totals"][key] = val
        result["steps"].append(result["totals"])
        return result

    # Structured parse: find SI lines, activity lines.
    for i, l in enumerate(lines):
        ls = l.strip()
        if ls.lower().startswith("si(") or ls.lower().startswith("saturation"):
            parts = ls.split()
            if len(parts) >= 2:
                name = parts[0].replace("si(", "").replace(")", "").replace("_", " ")
                try:
                    result["si"][name] = float(parts[-1])
                except ValueError:
                    pass
        if ls.lower().startswith("act("):
            parts = ls.split()
            if len(parts) >= 2:
                name = parts[0].replace("act(", "").replace(")", "")
                try:
                    result["activities"][name] = float(parts[-1])
                except ValueError:
                    pass
        if ls.startswith("Total") and "=" in ls:
            parts = ls.split("=")
            try:
                result["totals"][parts[0].strip()] = float(parts[1].split()[0])
            except (ValueError, IndexError):
                pass
    return result


def available() -> bool:
    """Whether a PHREEQC binary is present in this environment."""
    return bool(os.environ.get("PHREEQC_BIN") or shutil.which("phreeqc"))
